[leak_grade]
# define possible names for the leak grade field
leak_grade_aliases = Leak Grade, Grado Fuga, Grado fuga, Leak Grade Dropdown, Leak Grade 2iRete, Leak Grade Apreti, Reti-MT leak Grade, Leak Grade GRDF, Leak grade 2IRETEGAS, Leak Grade Italgas, Leak grade RetiPiu, Leak Grade DEPA
other_leak_grade_list = A1, A2, B, C, No Grade, 1, 2, 3, Prelocalizzata

[leak_type]
# define possible names for the leak type field
leak_type_aliases = Leak Type, Leak Type ITALGAS, Tipo di fuga, Leak Type 2IRETEGAS, Leak Type RetiPiu, Tipologia localizzazione dispersione, Leak Type EU-IT
other_leak_types_list = NC, Interrata, Aerea, Dans le sol, Au-dessus du sol, Sotto terra, Sopra terra
ag_alias_list = Aerea, Au-dessus du sol, Sopra terra
bg_alias_list = Interrata, Dans le sol, Sotto terra

[leak_location]
# define possible names for the leak location field
leak_location_aliases = Leak Location, Leak Location ITALGAS, Leak Location Toscana v2, Leak Location 2IRETEGAS, Leak Location RetiPiu, Posizione Dispersione, Leak Location EU-IT

[readings]
# define possible names for the leak location field
surface_reading_alias = Surface Reading
surface_unit_alias = Reading Unit, Reading Unit Surface Italgas, Reading Unit Surface 2IRETEGAS, Reading Unit - Surface, Reading Unit Surface RetiPiu, Reading Unit Surface EU-IT
barhole_reading_alias = Barhole Reading
barhole_unit_alias = Reading Unit Barhole Italgas, Reading Unit Barhole 2IRETEGAS, Reading Unit - Barhole, Reading Unit Barhole RetiPiu, Reading Unit Barhole EU-IT

[city]
city_aliases = City, City RetiPiu